name: quiz
description: "A Quiz app built in Flutter as part of learning and practicing"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  freezed: ^3.0.3

flutter:

  uses-material-design: true

